heroku:
    stage: deploy
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/telegram-bot-clima-test.git
        - git branch --all
        - git push heroku main:master
        - heroku ps:scale clock=1
