heroku:
    stage: deploy
    only: 
        - master
    script:
        - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/telegram-bot-clima-test.git
        - git push -f heroku master
        - heroku ps:scale clock=1
